---
apiVersion: v1
kind: Template
labels:
  app: wikijs
  template: wikijs
metadata:
  name: wikijs
  template.openshift.io/bindable: "false"
parameters:
  - name: NAME
    value: wikijs
  - name: HOST
    required: false
  - name: LETSENCRYPT_ENABLED
    value: "false" 
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      annotations:
        kubernetes.io/tls-acme: '${LETSENCRYPT_ENABLED}'
      name: ${NAME}
    spec:
      host: ${HOST}
      port:
        targetPort: wikijs
      tls:
        termination: edge
      to:
        kind: Service
        name: ${NAME}
        weight: 100
      wildcardPolicy: None
