---
apiVersion: v1
kind: Template
labels:
  app: wikijs
  template: wikijs
metadata:
  name: wikijs
  template.openshift.io/bindable: "false"
parameters:
  - displaName: Name
    name: NAME
    required: true
    value: wikijs
  - displayName: Database Name
    name: DATABASE_NAME
    required: true
    value: wiki
  - displayName: Database User Name
    name: DATABASE_USER
    required: true
    value: wiki
  - displayName: Database User Password
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    name: DATABASE_PASSWORD
  - displayName: Database Admin Password
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    name: DATABASE_ADMIN_PASSWORD
  - displayName: Session Secret
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    name: SESSION_SECRET

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-db
    stringData:
      database-name: ${DATABASE_NAME}
      database-user: ${DATABASE_USER}
      database-password: ${DATABASE_PASSWORD}
      database-admin-password: ${DATABASE_ADMIN_PASSWORD}
      session-secret: ${SESSION_SECRET}
